using System.Collections.Concurrent;
using System.Runtime.CompilerServices;
using Farol.Engine.Navigation;
using Microsoft.CodeAnalysis;
using CSharpSyntax = Microsoft.CodeAnalysis.CSharp.Syntax;
using VisualBasicSyntax = Microsoft.CodeAnalysis.VisualBasic.Syntax;

namespace Farol.Engine.Legacy;

/// <summary>Where an external API comes from.</summary>
public enum ApiOrigin
{
    NetFramework,
    ModernNet,
    Package,
    Other,
}

public sealed record UsageLocation(string FilePath, int Line);

/// <summary>One external (metadata) API a project's code uses, with every line that uses it.</summary>
public sealed record ApiUsage(string Id, string FullName, string Namespace, string Display, ApiOrigin Origin, IReadOnlyList<UsageLocation> Locations)
{
    public LegacyTechnology? Technology => LegacyCatalog.Match(FullName);
}

/// <summary>
/// The external APIs each project's own code uses: every name the semantic model binds to a type or member of a
/// referenced assembly. Generated code (designer files, XAML and source-generator output) is left out: what it uses
/// comes from markup that gets migrated anyway. Computed once per project and snapshot.
/// </summary>
public static class ApiUsageScanner
{
    /// <summary>"System.Web.UI.Page", "System.Configuration.ConfigurationManager.AppSettings": what the catalog matches.</summary>
    private static readonly SymbolDisplayFormat FullNameFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.None);

    /// <summary>"BinaryFormatter.Serialize(Stream, object)": short, with parameter types to tell overloads apart.</summary>
    private static readonly SymbolDisplayFormat DisplayFormat = new(
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypes,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
        memberOptions: SymbolDisplayMemberOptions.IncludeParameters | SymbolDisplayMemberOptions.IncludeContainingType,
        parameterOptions: SymbolDisplayParameterOptions.IncludeType,
        miscellaneousOptions: SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    private static readonly ConditionalWeakTable<Solution, ConcurrentDictionary<ProjectId, Lazy<Task<IReadOnlyList<ApiUsage>>>>> Cache = new();

    public static Task<IReadOnlyList<ApiUsage>> ScanAsync(Project project, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(project);

        // Computed without the caller's token: a cancelled request must not leave a cancelled result in the cache.
        var scans = Cache.GetValue(project.Solution, _ => new ConcurrentDictionary<ProjectId, Lazy<Task<IReadOnlyList<ApiUsage>>>>());
        var scan = scans.GetOrAdd(project.Id, _ => new Lazy<Task<IReadOnlyList<ApiUsage>>>(() => ScanCoreAsync(project)));
        return scan.Value.WaitAsync(cancellationToken);
    }

    /// <summary>True for designer files, XAML and source-generator output, and files that declare themselves auto-generated.</summary>
    public static bool IsGenerated(string? filePath, SyntaxNode? root = null)
    {
        if (filePath is not null)
        {
            var name = Path.GetFileName(filePath);
            if (name.Contains(".designer.", StringComparison.OrdinalIgnoreCase)
                || name.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) || name.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
                || name.EndsWith(".g.vb", StringComparison.OrdinalIgnoreCase) || name.EndsWith(".g.i.vb", StringComparison.OrdinalIgnoreCase)
                || name.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase)
                || name.EndsWith(".AssemblyAttributes.cs", StringComparison.OrdinalIgnoreCase) || name.EndsWith(".AssemblyAttributes.vb", StringComparison.OrdinalIgnoreCase)
                || filePath.Replace('\\', '/').Contains("/obj/", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return root is not null && root.GetLeadingTrivia().ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
    }

    private static async Task<IReadOnlyList<ApiUsage>> ScanCoreAsync(Project project)
    {
        var compilation = await project.GetCompilationAsync();
        if (compilation is null)
        {
            return [];
        }

        var found = new ConcurrentDictionary<ISymbol, ConcurrentDictionary<UsageLocation, byte>>(SymbolEqualityComparer.Default);
        await Parallel.ForEachAsync(project.Documents.Where(d => d.FilePath is not null && !IsGenerated(d.FilePath)), async (document, token) =>
        {
            var root = await document.GetSyntaxRootAsync(token);
            var model = await document.GetSemanticModelAsync(token);
            if (root is null || model is null || IsGenerated(document.FilePath, root))
            {
                return;
            }

            foreach (var node in root.DescendantNodes())
            {
                if (node is not (CSharpSyntax.SimpleNameSyntax or VisualBasicSyntax.SimpleNameSyntax))
                {
                    continue;
                }

                var info = model.GetSymbolInfo(node, token);
                var symbol = Normalize(info.Symbol ?? info.CandidateSymbols.FirstOrDefault());
                if (symbol?.ContainingAssembly is null || symbol.Locations.Any(l => l.IsInSource))
                {
                    continue;
                }

                var line = node.GetLocation().GetLineSpan().StartLinePosition.Line + 1;
                found.GetOrAdd(symbol, _ => new ConcurrentDictionary<UsageLocation, byte>()).TryAdd(new UsageLocation(document.FilePath!, line), 0);
            }
        });

        var origins = new Dictionary<IAssemblySymbol, ApiOrigin>(SymbolEqualityComparer.Default);
        return [.. found
            .Select(kv => new ApiUsage(
                SymbolFormatter.Id(kv.Key),
                kv.Key is INamedTypeSymbol ? kv.Key.ToDisplayString(FullNameFormat) : $"{kv.Key.ContainingType?.ToDisplayString(FullNameFormat)}.{kv.Key.Name}",
                (kv.Key as INamedTypeSymbol ?? kv.Key.ContainingType)?.ContainingNamespace is { IsGlobalNamespace: false } ns ? ns.ToDisplayString() : string.Empty,
                kv.Key.ToDisplayString(DisplayFormat),
                OriginOf(compilation, kv.Key.ContainingAssembly, origins),
                [.. kv.Value.Keys.OrderBy(l => l.FilePath, StringComparer.OrdinalIgnoreCase).ThenBy(l => l.Line)]))
            .OrderBy(u => u.FullName, StringComparer.Ordinal)
            .ThenBy(u => u.Id, StringComparer.Ordinal)];
    }

    /// <summary>
    /// The API a name stands for: a type for its constructors (what a migration replaces is the type), the property for
    /// an accessor, the definition for generic instantiations and reduced extension methods; nothing for locals,
    /// parameters, namespaces and built-in types.
    /// </summary>
    private static ISymbol? Normalize(ISymbol? symbol) => symbol switch
    {
        IAliasSymbol alias => Normalize(alias.Target),
        IArrayTypeSymbol array => Normalize(array.ElementType),
        IPointerTypeSymbol pointer => Normalize(pointer.PointedAtType),
        INamedTypeSymbol { SpecialType: not SpecialType.None } or INamedTypeSymbol { IsTupleType: true } => null,
        INamedTypeSymbol type => type.OriginalDefinition,
        IMethodSymbol { MethodKind: MethodKind.Constructor or MethodKind.StaticConstructor } constructor => Normalize(constructor.ContainingType),
        IMethodSymbol { ReducedFrom: { } reduced } => reduced.OriginalDefinition,
        IMethodSymbol { AssociatedSymbol: { } property } => property.OriginalDefinition,
        IMethodSymbol { MethodKind: MethodKind.Ordinary or MethodKind.UserDefinedOperator or MethodKind.Conversion } method => method.OriginalDefinition,
        IPropertySymbol or IFieldSymbol or IEventSymbol => symbol.OriginalDefinition,
        _ => null,
    };

    private static ApiOrigin OriginOf(Compilation compilation, IAssemblySymbol assembly, Dictionary<IAssemblySymbol, ApiOrigin> cache)
    {
        if (cache.TryGetValue(assembly, out var known))
        {
            return known;
        }

        var path = (compilation.GetMetadataReference(assembly) as PortableExecutableReference)?.FilePath?.Replace('\\', '/');
        var origin = path switch
        {
            null => ApiOrigin.Other,
            _ when path.Contains("/Reference Assemblies/Microsoft/Framework/", StringComparison.OrdinalIgnoreCase)
                || path.Contains("/microsoft.netframework.referenceassemblies", StringComparison.OrdinalIgnoreCase)
                || path.Contains("/Microsoft.NET/Framework", StringComparison.OrdinalIgnoreCase)
                || path.Contains("/Microsoft.NET/assembly/", StringComparison.OrdinalIgnoreCase) => ApiOrigin.NetFramework,
            _ when path.Contains("/packs/", StringComparison.OrdinalIgnoreCase)
                || path.Contains(".app.ref/", StringComparison.OrdinalIgnoreCase) => ApiOrigin.ModernNet,
            _ when MetadataSource.IsPackageAssembly(path) => ApiOrigin.Package,
            _ => ApiOrigin.Other,
        };
        cache[assembly] = origin;
        return origin;
    }
}
