//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy.Web
{
    public partial class _Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblTotal;

        protected global::System.Web.UI.WebControls.Button btnCalculate;
    }
}
