using System.Windows;
using Legacy.Core.Orders;

namespace Legacy.Wpf
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            // InitializeComponent and TotalText come from MainWindow.g.cs, generated by the XAML compiler.
            InitializeComponent();
        }

        private void OnCalculateClick(object sender, RoutedEventArgs e)
        {
            var calculator = new OrderCalculator(new InMemoryOrderRepository());
            TotalText.Text = calculator.GetTotal(1).ToString("C");
        }
    }
}
